from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Literal
from datetime import datetime

# ------------------------------
# Step 25: RawPageBundle
# ------------------------------
@dataclass
class RawPageBundle:
    url: str
    html: str
    fetched_at: str  # ISO datetime string
    source: Literal["direct", "brightdata"]
    status_code: int

# ------------------------------
# Step 26: SanitizedRecord
# ------------------------------
@dataclass
class SanitizedRecord:
    title: str
    category: str
    price: float
    currency: str = "GBP"
    rating: Optional[int] = None
    availability: Optional[str] = None
    source_url: str = ""

# ------------------------------
# Step 27: SchemaProfile
# ------------------------------
@dataclass
class SchemaProfile:
    table_name: str
    columns: List[Dict[str, Any]]  # list of {name, dtype, null_ratio}
    row_count: int

# ------------------------------
# Step 28: CorrelationResult
# ------------------------------
@dataclass
class CorrelationResult:
    matrix: Dict[str, Dict[str, float]]
    columns: List[str]

# ------------------------------
# Step 29: BinnedStatsResult
# ------------------------------
@dataclass
class BinnedStatsResult:
    column: str
    bin_edges: List[float]
    counts: List[int]

# ------------------------------
# Step 30: GroupStatsResult
# ------------------------------
@dataclass
class GroupStatsResult:
    group_column: str
    value_column: str
    groups: List[Dict[str, Any]]  # each dict: {group_name, n, mean, median, std, skewness, kurtosis}

# ------------------------------
# Step 31: ClassBalanceResult
# ------------------------------
@dataclass
class ClassBalanceResult:
    label_column: str
    class_counts: Dict[str, int]
    imbalance_ratio: float  # majority / minority

# ------------------------------
# Step 32: TimeSeriesStatsResult
# ------------------------------
@dataclass
class TimeSeriesStatsResult:
    time_column: str
    value_column: str
    rolling_mean_by_bucket: List[float]
    rolling_var_by_bucket: List[float]
    lag1_autocorr: float

# ------------------------------
# Step 33: ProfileBundle (Container)
# ------------------------------
@dataclass
class ProfileBundle:
    schema_profile: Optional[SchemaProfile] = None
    missing_values: Optional[Dict[str, float]] = None
    correlations: Optional[CorrelationResult] = None
    binned_stats: Optional[BinnedStatsResult] = None
    group_stats: Optional[GroupStatsResult] = None
    class_balance: Optional[ClassBalanceResult] = None
    time_series_stats: Optional[TimeSeriesStatsResult] = None

# ------------------------------
# Step 34: AuditVerdict
# ------------------------------
@dataclass
class AuditVerdict:
    task_type: Literal["group_comparison", "regression", "classification", "timeseries"]
    passed: bool
    findings: List[str] = field(default_factory=list)
    recommended_test_or_model: str = ""
    excluded_groups: Optional[List[str]] = None

# ------------------------------
# Step 35: VizSpec
# ------------------------------
@dataclass
class VizSpec:
    chart_type: str
    x: str
    y: Optional[str]
    title: str
    x_label: str
    y_label: Optional[str]
    output_filename: str
    
    
# ============================================================
# Additional dataclasses needed for orchestration
# ============================================================

@dataclass
class StructuredTask:
    """Parsed user query into structured analysis task."""
    task_type: Literal["group_comparison", "regression", "classification", "timeseries"]
    target_domain: str
    group_column: Optional[str] = None
    value_column: Optional[str] = None
    time_column: Optional[str] = None
    label_column: Optional[str] = None
    visualization_requested: bool = True


@dataclass
class LLMResponse:
    """Response from the language model."""
    content: str
    tool_calls: Optional[List[Dict[str, Any]]] = None
    input_tokens: int = 0
    output_tokens: int = 0
    latency_ms: int = 0


@dataclass
class GeneratedScript:
    """Script generated by the AI for analysis."""
    code: str
    script_path: str
    attempt_number: int = 1


@dataclass
class ExecutionResult:
    """Result of running the script in the sandbox."""
    success: bool
    stdout: str
    stderr: str
    artifact_paths: List[str]
    duration_ms: int


@dataclass
class ReportBundle:
    """All artifacts and metadata for the final report."""
    task: StructuredTask
    audit: AuditVerdict
    artifacts: List[str]
    metrics: Dict[str, Any]


@dataclass
class BrokerRequest:
    """Request to the broker process."""
    operation: str
    params: Dict[str, Any]


@dataclass
class BrokerResponse:
    """Response from the broker process."""
    ok: bool
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


@dataclass
class IngestionResult:
    """Result of ingesting records into the database."""
    table_name: str
    row_count: int
    column_count: int
    warnings: List[str]


@dataclass
class InjectionFlag:
    """Detected injection pattern in scraped HTML."""
    url: str
    location_hint: str
    pattern_matched: str
    snippet_hash: str  # hash only, never the raw text
    


@dataclass
class SanitizedRecord:
    title: str
    category: str = ""            # optional
    price: float = 0.0
    currency: str = "GBP"
    rating: Optional[int] = None
    availability: Optional[str] = None
    source_url: str = ""
    
@dataclass
class ModelConfig:
    """Configuration for the language model."""
    model_name: str = "gemini-2.5-flash"
    temperature: float = 0.2
    max_output_tokens: int = 4096

@dataclass
class LLMResponse:
    """Response from the language model."""
    content: str
    tool_calls: Optional[List[Dict[str, Any]]] = None
    input_tokens: int = 0
    output_tokens: int = 0
    latency_ms: int = 0
    
@dataclass
class SandboxPolicy:
    network_mode: str = "none"
    memory_limit_mb: int = 1024
    cpu_limit: float = 1.0
    timeout_sec: int = 60